#
# File    : docker-compose.yaml
# Purpose : deploy a dvwa / kali environment
#
# Author  : Harald van der Laan
# Version : v1.0.0
# Date    : 2024-10-24
#

---
# Create networks for the dvwa / kali environment
networks:
  dvwa:

# Create volumes for the dvwa / kali environment for persistant data
volumes:
  dvwa-db:
  dvwa-kali:

# Creating containers for the dvwa / kali environment
services:
  dvwa-db:
    container_name: dvwa-db
    image: docker.io/library/mariadb:10
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa-db:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped

  dvwa:
    container_name: dvwa
    image: ghcr.io/digininja/dvwa:latest
    pull_policy: always
    environment:
      - PUID=501
      - PGID=20
      - DB_SERVER=dvwa-db
    depends_on:
      - dvwa-db
    networks:
      - dvwa
    restart: unless-stopped

  dvwa-kali:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: dvwa-kali
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Amsterdam
      - "TITLE=Workshop Kali Linux" #optional
    volumes:
      - dvwa-kali:/config
    networks:
      - dvwa
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:3001:3001
    shm_size: "2gb"
    restart: unless-stopped
